### PR TITLE
Adjust edge queries to support multiple sort columns

### LINKED ISSUE #1750: GraphQL pagination doesn't work with nullsPlacement
If you are fetching a connection and defined your own order by with nullsPlacement, when you paginate, the generated clause doesn't account for null values. For instance, if your custom `CustomClauseQuery` generates the following SQL

```sql
SELECT
  DISTINCT *
FROM
  horses
WHERE
  (
    sire_id = $ 1
    OR dam_id = $ 2
  )
ORDER BY
  birth_year DESC NULLS LAST
  id DESC
LIMIT
  1001
```

The pagination query ends up looking like this:

```sql
SELECT
  DISTINCT *
FROM
  horses
WHERE
  (
    sire_id = $ 1
    OR dam_id = $ 2
  )
  AND (
    birth_year < $ 3
    OR (
      birth_year = $ 4
      AND id < $ 5
    )
  )
ORDER BY
  birth_year DESC NULLS LAST
  id DESC
LIMIT
  1001
```

But since I wasn't filtering by birth year to begin with, all entries with a null birth year will now not be included in the pagination.

### PR DESCRIPTION
**Pull request by Swahvay**
When using `BaseEdgeQuery`, if you are sorting over multiple non-unique columns, the pagination was coming back incorrectly because the cursor was only storing a single sort column (plus the cursor key, usually the primary key uuid). This changes queries to allow for any number of sort columns and to run through the same SQL-generation despite the amount or type of sorting going on.

Fixes #1750 and #1751

### CODE REVIEW

File: ts/src/core/ent.ts [hunk 1]
```diff
@@ -1284,7 +1284,7 @@ export function getCursor(opts: cursorOptions) {
   }
   const convert = (d: any) => {
     if (d instanceof Date) {
-      return d.getTime();
+      return d.toISOString();
```
[the remark this answers is not in the document]
Comment (lolopinto) [reply ts/src/core/ent.ts:1287]: this makes sense. i don't recall if this is in the cursor somewhere. does this break something?

File: ts/src/core/query/query.ts [hunk 2]
```diff
@@ -125,7 +128,7 @@ function assertValidCursor(cursor: string, opts: validCursorOptions): any {
   if (parts.length !== keys.length * 2) {
     throw new Error(`invalid cursor ${cursor} passed`);
   }
-  const values: any = [];
+  const values: [key: string, value: string | number | null][] = [];
```
Comment (lolopinto) [inline ts/src/core/query/query.ts:131]: wowza. what's this type?

is this a fancy TS tuple? i had forgotten this could be done... I guess I don't write enough TS anymore

Comment (lolopinto) [inline ts/src/core/query/query.ts:131]: this needs some comments

File: ts/src/core/query/query.ts [hunk 3]
```diff
@@ -174,22 +177,21 @@ interface LastFilterOptions<T extends Data> extends FilterOptions<T> {
...
 
 class FirstFilter<T extends Data> implements EdgeQueryFilter<T> {
-  private offset: any | undefined;
-  private sortCol: string;
+  private offset: string | number | undefined;
   private edgeQuery: BaseEdgeQuery<Ent, Ent, T>;
   private pageMap: Map<ID, PaginationInfo> = new Map();
   private usedQuery = false;
-  private cursorValues: any[] = [];
+  private cursorKeyValues: [key: string, value: string | number | null][] = [];
```
Comment (lolopinto) [inline ts/src/core/query/query.ts:184]: second place. type alias seems to make sense

File: ts/src/core/query/query.ts [hunk 4]
```diff
@@ -174,22 +177,21 @@ interface LastFilterOptions<T extends Data> extends FilterOptions<T> {
...
 
-    this.sortCol = options.sortCol;
     if (options.after) {
-      this.cursorValues = assertValidCursor(options.after, {
+      this.cursorKeyValues = translateCursorToKeyValues(options.after, {
         keys: options.cursorKeys,
       });
-      this.offset = this.cursorValues[0];
+      this.offset =
+        this.cursorKeyValues[this.cursorKeyValues.length - 1][1] ?? undefined;
```
[the remark this answers is not in the document]
Comment (lolopinto) [reply ts/src/core/query/query.ts:194]: this needs comments in the code

File: ts/src/core/query_impl.ts [hunk 5]
```diff
@@ -9,6 +9,7 @@ export interface OrderByOption {
   // needed to know if we create a cursor based on this column to conver to timestamp and ISO string for
   // comparison
   // maybe eventually want a more generic version of this but for now this suffices
+  // @deprecated You no longer need to specify if a column is a date column
```
Comment (lolopinto) [inline ts/src/core/query_impl.ts:12]: you can just kill it. and we'll add this as a breaking 2.0 change that i keep forgetting to do

**Review by lolopinto — COMMENTED** [review]
direction/code makes sense to me and seems easier to read than current state of things.

thanks for diving in and making changes.

adding tests for the complicated new clause and something that makes sure existing tests still work + new tests for a complicated case woud be great

File: ts/src/core/query/query.ts (hunk 2 above)
Comment (Swahvay) [reply ts/src/core/query/query.ts:131]: Yeah, it's just a tuple, but you can name each piece in TS now.

File: ts/src/core/clause.ts [hunk 6]
```diff
@@ -1371,6 +1371,63 @@ export function PaginationMultipleColsSubQuery<T extends Data, K = keyof T>(
...
+ * When paginating over multiple ordered columns, we need to construct a nested
+ * set of clauses to correctly filter. The resulting query will be structured as
+ * a group of nested ANDs and ORs.
+ *
+ * For example, given a set of ordering [{col1, less1}, {col2, greater2}], the
+ * function will construct a query that looks like:
+ *
+ * (col1 < $1 OR (col1 = $1 AND col2 > $2))
+ */
+export function PaginationUnboundColsQuery<T extends Data, K = keyof T>(
```
[the remark this answers is not in the document]
Comment (Swahvay) [reply ts/src/core/clause.ts:1384]: Ummm, for this to work we'd then also need to have a max on the order by field list. I don't think it necessarily needs a max. It might make the cursor itself long, but I don't see it being a problem.

File: ts/src/core/ent.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (Swahvay) [reply ts/src/core/ent.ts:1287]: I don't think this will break anything unless people were storing cursors for some reason, but these should just be used with each request so it would just generate a different cursor than before and be fine.

File: ts/src/core/clause.ts [hunk 7]
```diff
@@ -1371,6 +1371,63 @@ export function PaginationMultipleColsSubQuery<T extends Data, K = keyof T>(
...
+  ordering: {
+    sortCol: K;
+    direction: "ASC" | "DESC";
+    sortValue: string | number | null;
+    nullsPlacement?: "first" | "last";
+    overrideAlias?: string;
+  }[],
```
[the remark this answers is not in the document]
Comment (Swahvay) [reply ts/src/core/clause.ts:1391]: Sure 👍

**Comment by Swahvay** [comment]
Ok, I'll get on fixing the tests and adding some new ones with complicated ordering. 👍

File: ts/src/core/ent.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (Swahvay) [reply ts/src/core/ent.ts]: So, this actually did break things so I needed to change the logic. I think the reason you had done `d.getTime()` to begin with was because you were storing the cursor as `<key>:<value>`, and `d.getISOString()` returns a string with `:`s. So, when you did `cursor.split(':')` it failed. I changed this to be an array of key/value tuples that I just `JSON.stringify`ed and that works for everything.

**Comment by Swahvay** [comment]
I don't _think_ the file upload test failures are mine, but I don't know enough about them to be sure.

File: ts/src/core/clause.ts [hunk 8]
```diff
@@ -1371,6 +1377,65 @@ export function PaginationMultipleColsSubQuery<T extends Data, K = keyof T>(
...
+        const clauseFn = direction === "DESC" ? Less : Greater;
+        const baseClause = clauseFn(sortCol, sortValue, overrideAlias);
+        const withNullsClause =
+          sortValue !== null
+            ? nullsOrder === "last"
+              ? Or(baseClause, Eq(sortCol, null, overrideAlias))
+              : And(baseClause, NotEq(sortCol, null, overrideAlias))
+            : nullsOrder === "last"
+              ? Eq(sortCol, null, overrideAlias)
+              : undefined; // If nulls first and value is null, can't filter here
```
Comment (lolopinto) [inline ts/src/core/clause.ts:1420]: this is hard to read...

Comment (lolopinto) [inline ts/src/core/clause.ts:1420]: still feels like we need more comments here

File: ts/src/core/clause.ts [hunk 9]
```diff
@@ -1499,3 +1564,34 @@ export function Expression<T extends Data, K = keyof T>(
 ): Clause<T, K> {
   return new simpleExpression(expression);
 }
+
+export function ClauseGroup<T extends Data, K = keyof T>(
+  clause: Clause<T, K>,
+): Clause<T, K> {
+  return new groupClause(clause);
+}
```
Comment (lolopinto) [inline ts/src/core/clause.ts:1572]: what does a ClauseGroup mean?

File: ts/src/core/db.ts [hunk 10]
```diff
@@ -441,15 +440,15 @@ export class Postgres implements Connection {
...
+    return r as QueryResult<QueryResultRow>;
   }
 
   async queryAll(
     query: string,
     values?: any[],
   ): Promise<QueryResult<QueryResultRow>> {
     const r = await this.pool.query(query, values);
-    return r;
+    return r as QueryResult<QueryResultRow>;
```
Comment (lolopinto) [inline ts/src/core/db.ts:451]: hmm, why did we need this series of changes?

File: ts/src/core/ent.ts [hunk 11]
```diff
@@ -1261,43 +1261,44 @@ export class AssocEdge {
...
-  const parts: string[] = [];
-  for (let i = 0; i < keys.length; i++) {
-    const key = keys[i];
-    const cursorKey = cursorKeys?.[i] || key;
-    parts.push(key);
-    parts.push(convert(row[cursorKey]));
+  const parts: [string, string | number | null][] = [];
+  for (let i = 0; i < cursorKeys.length; i++) {
+    const key = cursorKeys[i];
+    const cursorKey = rowKeys?.[i] || key;
```
Comment (lolopinto) [inline ts/src/core/ent.ts:1298]: these names should be fixed. it's confusing...

File: ts/src/core/query/query.ts [hunk 12]
```diff
@@ -98,63 +97,33 @@ interface validCursorOptions {
...
+  opts: validCursorOptions,
+): CursorKeyValues {
   const { keys } = opts;
+  const decoded = atob(cursor);
+  let cursorData: CursorKeyValues = [];
+  try {
+    cursorData = JSON.parse(decoded);
+  } catch (error) {
+    throw new Error(`Bad cursor format ${cursor} passed`);
+  }
```
Comment (lolopinto) [inline ts/src/core/query/query.ts:113]: can you write something about what changed here? this is a breaking change

this might be the final PR that forces the v0.2.0 and happy yo make it clear

**Review by lolopinto — APPROVED** [review]

File: ts/src/core/clause.ts (hunk 9 above)
Comment (Swahvay) [reply ts/src/core/clause.ts:1572]: I needed something for testing, but this actually is helpful in other ways to just group a clause in parentheses. So if you had:
```js
And(
  Or(Eq('x', 1), Eq('x', 2)), 
  Or(Eq('y', 1), Eq('y', 2)),
)
```
It would generate `x = 1 OR x = 2 AND y = 1 OR y = 2`, but SQL groups `AND`s before `OR`s, so that would actually get executed as `x = 1 OR (x = 2 AND y = 1) OR y = 2`. The `ClauseGroup` just allows you control that. So you could do:
```js
And(
  ClauseGroup(Or(Eq('x', 1), Eq('x', 2))),
  ClauseGroup(Or(Eq('y', 1), Eq('y', 2))),
)
```
which would then be evaluated to `(x = 1 OR x = 2) AND (y = 1 OR y = 2)`.

Comment (Swahvay) [reply ts/src/core/clause.ts:1572]: Arguably this might be something that `And` and `Or` should do inherently, but honestly I was kinda scared to go down that rabbit hole.

Comment (Swahvay) [reply ts/src/core/clause.ts:1572]: Happy to rename this to just `Parentheses` if you think that's better.

File: ts/src/core/db.ts (hunk 10 above)
Comment (Swahvay) [reply ts/src/core/db.ts:451]: My build kept failing without these. Maybe I'm using a later TS version? Not sure, but I can revert them if you want.

File: ts/src/core/query/query.ts (hunk 12 above)
Comment (Swahvay) [reply ts/src/core/query/query.ts:113]: You mean as a description for a changelog, right? Not literally in the code.

File: ts/src/core/clause.ts (hunk 8 above)
Comment (Swahvay) [reply ts/src/core/clause.ts:1420]: Yeah I can do that

File: ts/src/core/ent.ts (hunk 11 above)
Comment (Swahvay) [reply ts/src/core/ent.ts:1298]: image

File: ts/src/core/clause.ts (hunk 9 above)
Comment (Swahvay) [reply ts/src/core/clause.ts:1572]: Oh I'm looking now and `Or`/`And` do add parentheses. I remember adding it so the generated SQL matched exactly but now when I try it without using `ClauseGroup` it works just the same. I must've been doing something wrong at the time. I'll remove it.

File: ts/src/core/query/query.ts (hunk 12 above)
Comment (Swahvay) [reply ts/src/core/query/query.ts:113]: Here's a description:

Cursor values for GraphQL connections have changed, along with how pagination works under the hood. Previously, pagination would only account for a single sort column (not including the primary key for the table). This meant you could paginate a result of users that were sorted by `birthday`, but it would produce incorrect results if you tried to sort by `birthday` and `name`. Additionally, the placement of null values in the result set (first/last) was not preserved between the original fetch and subsequent pagination. Now you can sort by any number of columns and the pagination results will always reference the original sort order, including null placement.

If you were never sorting by more than one column other than the primary key you should not notice any changes. If you were sorting by multiple non-primary key columns, you will notice a more consistent and accurate pagination.

If you were storing graphQL connection cursors to be re-used across requests, you will need to update those cursors or change your implementation to only use the cursors returned from each request.

Comment (Swahvay) [reply ts/src/core/query/query.ts:113]: Oh, I should also add another note:

The `dateColumn` property in the `order` field of `EdgeQueryOptions` has been removed. You no longer need to manually specify fields as date types and can remove all reference to this property.
